on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target:
        required: true
        type: string
      py-arch:
        required: false
        type: string
      manylinux:
        required: false
        type: string
      release:
        required: true
        type: boolean

jobs:
  build:
    name: Build - ${{ inputs.os }} - ${{ inputs.target }}
    runs-on: ${{ inputs.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: ${{ inputs.py-arch || 'x64' }}
      - name: Install tomlkit to edit Cargo.toml
        run: pip install tomlkit
      - name: Run build helper
        run: python ./.github/dev-bumper.py ${{ github.sha }} ${{ inputs.release }} $GITHUB_ENV

      - name: Build wheels - ${{ inputs.target }}
        uses: PyO3/maturin-action@v1
        if: ${{ inputs.target != 'universal2' }}
        with:
          rust-toolchain: nightly
          target: ${{ inputs.target }}
          args: ${{ env.BASE_BUILD }}

      - name: Build wheels - universal2
        uses: PyO3/maturin-action@v1
        if: ${{ inputs.target == 'universal2' }}
        with:
          rust-toolchain: nightly
          args: ${{ env.BASE_BUILD }} --universal2

      - name: Build wheels - manylinux
        uses: PyO3/maturin-action@v1
        if: ${{ inputs.manylinux }}
        with:
          rust-toolchain: nightly
          target: ${{ inputs.target }}
          manylinux: ${{ inputs.manylinux }}
          args: ${{ env.BASE_BUILD }}

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist
