name: Compile Check

on:
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: PyO3/maturin-action@v1
      with:
        rust-toolchain: nightly
        manylinux: auto
        command: build
        args: --sdist -o dist --find-interpreter
    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: nightly-wheels
        path: dist